# Generated by Django 3.0.5 on 2020-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
